#!/usr/bin/env bash
# Prepare a Databricks workspace for the dbt v2 / Unity Catalog protocol.
#
# It discovers what the workspace offers (Unity Catalog metastore, catalogs, SQL
# warehouse), starts the warehouse, and writes env.local with every variable the
# live phase needs. Nothing is created in Unity Catalog unless you pass
# --with-cross-catalog: the fixture builds its own source table through a seed.
#
# Required: DBT_HOST, DBT_TOKEN (or --host / --token).
# Usage:
#   ./bootstrap.sh [--host <h>] [--token <t>] [--catalog <c>] [--schema <s>]
#                  [--warehouse <id>] [--with-cross-catalog [<name>]]
#
# Then:  source env.local && ./run_live_checks.sh
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
API="python3 $HERE/lib/dbx_api.py"
CATALOG=""; SCHEMA="dbt_uc_compat"; WAREHOUSE=""; CROSS=""; WANT_CROSS=0

while [ $# -gt 0 ]; do
  case "$1" in
    --host)      export DBT_HOST="$2"; shift 2 ;;
    --token)     export DBT_TOKEN="$2"; shift 2 ;;
    --catalog)   CATALOG="$2"; shift 2 ;;
    --schema)    SCHEMA="$2"; shift 2 ;;
    --warehouse) WAREHOUSE="$2"; shift 2 ;;
    --with-cross-catalog)
      WANT_CROSS=1
      case "${2:-}" in -*|"") CROSS="dbt_uc_compat_ext"; shift ;; *) CROSS="$2"; shift 2 ;; esac ;;
    -h|--help)   sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

: "${DBT_HOST:?set DBT_HOST or pass --host}"
: "${DBT_TOKEN:?set DBT_TOKEN or pass --token}"
export DBT_HOST DBT_TOKEN

step() { printf '\n\033[1m%s\033[0m\n' "$*"; }
note() { printf '  %s\n' "$*"; }
die()  { printf '  \033[31m%s\033[0m\n' "$*"; exit 1; }

step "Workspace identity"
$API whoami | sed 's/^/  /' || die "cannot authenticate against $DBT_HOST"

step "Unity Catalog"
ASSIGN="$($API metastore)"
note "$ASSIGN"
grep -q '"metastore_id": *"[^"]' <<<"$ASSIGN" || die "no Unity Catalog metastore assigned to this workspace"
DEFAULT_CATALOG="$(python3 -c 'import json,sys; print(json.loads(sys.argv[1]).get("default_catalog_name") or "")' "$ASSIGN")"
note "catalogs:"; $API catalogs | sed 's/^/    /'

if [ -z "$CATALOG" ]; then
  # Prefer a catalog we can write to: the workspace default, never a SYSTEM_CATALOG.
  CATALOG="$($API catalogs | awk -F'\t' '$2 != "SYSTEM_CATALOG" {print $1}' | grep -Fx "$DEFAULT_CATALOG" || true)"
  [ -z "$CATALOG" ] && CATALOG="$($API catalogs | awk -F'\t' '$2 != "SYSTEM_CATALOG" {print $1; exit}')"
fi
[ -z "$CATALOG" ] && die "no writable catalog found: pass --catalog"
note "target catalog: $CATALOG"

# `samples` ships with every workspace and gives the cross-catalog *read* check a
# real table in another catalog.
EXT_CATALOG="$($API catalogs | awk -F'\t' '$1 == "samples" {print $1}')"
if [ -n "$EXT_CATALOG" ]; then note "cross-catalog read source: samples.tpch.customer"; else
  note "no 'samples' catalog: the cross-catalog read check will run against $CATALOG"; fi

step "SQL warehouse"
[ -z "$WAREHOUSE" ] && WAREHOUSE="$($API pick-warehouse)"
$API warehouses | grep -F "$WAREHOUSE" | sed 's/^/  /'
note "starting $WAREHOUSE (this can take a minute)"
STATE="$($API start-warehouse "$WAREHOUSE")" || die "warehouse $WAREHOUSE did not start"
note "state: $STATE"
HTTP_PATH="/sql/1.0/warehouses/$WAREHOUSE"

step "Connectivity check through SQL"
$API sql "select current_catalog() as c, current_user() as u" | sed 's/^/  /' \
  || die "the warehouse is up but the statement failed"

if [ "$WANT_CROSS" -eq 1 ]; then
  step "Second catalog for the cross-catalog write check"
  note "creating catalog $CROSS (needs CREATE CATALOG on the metastore)"
  if $API sql "create catalog if not exists $CROSS comment 'dbt v2 UC compatibility protocol - safe to drop'" | grep -q '^\[SUCCEEDED\]'; then
    note "catalog $CROSS ready"
  else
    note "could not create $CROSS: the cross-catalog write check will be skipped"
    CROSS=""
  fi
fi

step "Writing env.local"
cat > "$HERE/env.local" <<EOF
# Generated by bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) - contains a token, never commit it.
export DBT_HOST='$DBT_HOST'
export DBT_TOKEN='$DBT_TOKEN'
export DBT_HTTP_PATH='$HTTP_PATH'
export DBX_WAREHOUSE='$WAREHOUSE'
export DBT_CATALOG='$CATALOG'
export DBT_SCHEMA='$SCHEMA'
# The declared source is fed by the seed that dbt itself creates.
export DBT_SOURCE_CATALOG='$CATALOG'
export DBT_SOURCE_SCHEMA='${SCHEMA}_bronze'
export DBT_SOURCE_TABLE='seed_bronze_customers'
export DBT_SOURCE_TS_COLUMN='_ingested_at'
# Read-only source in another UC catalog.
export DBT_EXT_CATALOG='${EXT_CATALOG:-$CATALOG}'
export DBT_EXT_SCHEMA='$([ -n "$EXT_CATALOG" ] && echo tpch || echo "$SCHEMA")'
$([ -n "$CROSS" ] && echo "export DBT_CROSS_CATALOG='$CROSS'")
EOF
chmod 600 "$HERE/env.local"
note "$HERE/env.local (chmod 600, git-ignored)"

step "Ready"
cat <<EOF
  source $HERE/env.local
  ./run_live_checks.sh          # execution-level checks
  ./verify_uc_state.sh          # assert what actually landed in Unity Catalog
  ./teardown.sh --yes           # remove everything the protocol created
EOF
